# 桥梁工程专业知识库

[ner_general]

"对象类型识别注意事项" = [
    "桥涵结构就是桥梁结构",
    "小型排水构造物应视为(桥梁结构)而不是（桥梁结构组成部分）",
]

"IFC实体类型识别注意事项" = [
    "规范实体为(桥梁结构)或者排水构造物或涵洞直接映射为IfcBridge",
    "小型排水构造物应视为(桥梁结构)而不是（桥梁结构组成部分）,直接映射为IfcBridge",
    "公路是IfcRoad实体，与公路规范是相关的。",
]

[global]
"领域常识" = [
    "高速公路中桥的意思是高速公路上的中桥，说的是桥梁规模，大桥和特大桥是两种不同的桥梁规模，规范不通用",
    "一级公路和高级公路是两种不同的道路类型,规范不通用，高速公路与一级公路不属于同一范畴",
    "设计使用年限和设计基准期是相同概念"
]

# 基本术语定义
"桥梁类型" = [
    "梁式桥", "拱式桥", "悬索桥", "斜拉桥", "刚架桥"
]

"桥梁材料" = [
    "钢筋混凝土", "预应力混凝土", "钢结构", "组合结构"
]

"桥梁构件" = [
    "桥面系", "主梁", "横梁", "支座", "桥墩", "桥台", "基础"
]

"桥梁规模" = [
    "特大桥", "大桥", "中桥", "小桥","涵洞"
]

[IFC_CLASS_DESCRIPTION]
"IfcBridge"="""
桥梁的IFC实体类型
该实体类型用于表示桥梁的几何形状、材料、构件和其他相关信息。
"""
"IfcBridgePart"="""
桥梁构件的IFC实体类型
该实体类型用于表示桥梁的组成部分，如主梁、支座、桥墩等。
"""
"IfcBridgeSegment"="""
桥梁段的IFC实体类型
该实体类型用于表示桥梁的不同段落或部分。
"""
"IfcPipeSegment"="""
管道段的IFC实体类型
该实体类型用于表示管道的连续部分，具有特定的长度和连接。
"""
"IfcFastener"="""
紧固件的IFC实体类型
该实体类型用于表示用于连接建筑构件的组件，如螺栓、螺钉和焊缝。
"""
"IfcWall"="""
墙的IFC实体类型
该实体类型用于表示建筑中垂直或倾斜的分隔结构。
"""
"IfcCivilElement"="""
土木工程构件的IFC实体类型
该实体类型用于表示包括道路、桥梁、tunnel等在内的土木工程的组成部分。
"""
"IfcPavement"="""
路面的IFC实体类型
该实体类型用于表示覆盖在道路或其他表面上的结构层，通常由沥青或混凝土制成。
"""
"IfcBeam"="""
梁的IFC实体类型
该实体类型用于表示横向支撑的水平结构构件。
"""
"IfcBuildingElementProxy"="""
建筑构件代理的IFC实体类型
该实体类型用于表示未由其他更具体的类型定义的建筑构件。它充当通用或占位符实体。
"""
"IfcFooting"="""
基础的IFC实体类型
该实体类型用于表示将结构载荷传递到地面的基础构件。
"""
"IfcSlab"="""
楼板的IFC实体类型
该实体类型用于表示水平或倾斜的结构平板，通常是建筑物的地板或屋顶。
"""
"IfcPile"="""
桩的IFC实体类型
该实体类型用于表示插入地面的长而细的结构构件，用于支撑建筑物或其他结构的载荷。
"""
"IfcColumn"="""
柱的IFC实体类型
该实体类型用于表示垂直的结构构件，用于支撑来自上方的载荷。
"""
"IfcBearing"="""
支座的IFC实体类型
该实体类型用于表示桥梁等工程结构的承重部件，用于传递上部结构的荷载至下部支撑结构。
"""
"IfcMember"="""
构件的IFC实体类型
该实体类型用于表示建筑结构中的线型构件，具有结构功能，但通常不归类为梁、柱或桁架。
"""
"IfcRoad"="""
道路的IFC实体类型
该实体类型用于表示道路的几何形状、材料、构件和其他相关信息。
"""