# 桥梁工程专业知识库

[ner_general]

"对象类型识别注意事项" = [
    "墙体（包括承重墙、非承重墙、外墙、内墙等）都属于建筑物构件",
    '当提到具体的墙体类型时，应将整个词组识别为一个建筑物构件实体'
]

"IFC实体类型识别注意事项" = [
    "建筑物直接映射为IfcBuilding",
    "楼梯不能映射为IfcSlab",
    "安全出口映射为IfcDoor，由门表示"
]

[global]
"建筑领域常识" = [
    "楼梯不是楼板"
]

[IFC_CLASS_DESCRIPTION]
"IfcSlab"="""
楼板的IFC实体类型
该实体类型用于表示楼板的几何形状、材料和其他相关信息。
"""
"IfcMember"="""
构件的IFC实体类型
该实体类型用于表示任何通用的结构构件，如桁架杆件或檩条。
"""
"IfcStairFlight"="""
楼梯段的IFC实体类型
该实体类型用于表示楼梯的一个连续的梯级序列，即从一个平台到另一个平台之间的阶梯序列。
"""
"IfcStair"="""
楼梯的IFC实体类型
该实体类型用于表示楼梯的整体结构，包含楼梯段、平台和其他相关构件。
"""
"IfcDoor"="""
门的IFC实体类型
该实体类型用于表示门构件，包括门扇、门框和其他相关信息。
"""
"IfcColumn"="""
柱的IFC实体类型
该实体类型用于表示柱子的几何形状、材料和其他相关信息。
"""
"IfcRailing"="""
栏杆的IFC实体类型
该实体类型用于表示栏杆的几何形状、材料和其他相关信息。
"""
"IfcWindow"="""
窗户的IFC实体类型
该实体类型用于表示窗户构件，包括窗框、窗扇和其他相关信息。
"""
"IfcWall"="""
墙的IFC实体类型
该实体类型用于表示墙体的几何形状、材料和其他相关信息。
"""
"IfcOpeningElement"="""
开口元素的IFC实体类型
该实体类型用于表示墙体、楼板或其他构件上的开口，如门窗洞口。
"""
"IfcBeam"="""
梁的IFC实体类型
该实体类型用于表示梁的几何形状、材料和其他相关信息。
"""
"IfcSpace"="""
空间的IFC实体类型
该实体类型用于表示建筑内部定义的空间区域。
"""
"IfcSite"="""
场地的IFC实体类型
该实体类型用于表示建筑物所在的场地信息。
"""
"IfcBuildingStorey"="""
楼层的IFC实体类型
该实体类型用于表示建筑物中的一个楼层。
"""
"IfcBuilding"="""
建筑物的IFC实体类型
该实体类型用于表示建筑物整体的结构和属性。
"""